// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOf1ag8P5dL-9cki2OYmCxkz0vlW4Eh8A',
    appId: '1:827922499179:web:bb858eb13fc440df3e132e',
    messagingSenderId: '827922499179',
    projectId: 'shootinglogflutter-d9e64',
    authDomain: 'shootinglogflutter-d9e64.firebaseapp.com',
    storageBucket: 'shootinglogflutter-d9e64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tNtNWSzBPrF_w0FMYDOHkvoOz0LbN7M',
    appId: '1:827922499179:android:cbaa84bd1a2c90ef3e132e',
    messagingSenderId: '827922499179',
    projectId: 'shootinglogflutter-d9e64',
    storageBucket: 'shootinglogflutter-d9e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXh5PrENpuF5IHnrhevMbMYvdlkZ0fs4',
    appId: '1:827922499179:ios:340874189b93ce0e3e132e',
    messagingSenderId: '827922499179',
    projectId: 'shootinglogflutter-d9e64',
    storageBucket: 'shootinglogflutter-d9e64.appspot.com',
    iosBundleId: 'com.example.shootingLogFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvXh5PrENpuF5IHnrhevMbMYvdlkZ0fs4',
    appId: '1:827922499179:ios:9c994448ad05e0623e132e',
    messagingSenderId: '827922499179',
    projectId: 'shootinglogflutter-d9e64',
    storageBucket: 'shootinglogflutter-d9e64.appspot.com',
    iosBundleId: 'com.example.shootingLogFlutter.RunnerTests',
  );
}
